### ISSUE TITLE
is the search debounce needed?

### ISSUE THREAD

**Issue by 4www** [oskarrough/ember-jets#4]
https://github.com/oskarrough/ember-jets/blob/master/addon/components/jets-search.js#L66
Or maybe the default `wait` could to be `0` as it gives a "laggy" feeling to the search experience.

Is the debounce here for large data sets? Jets seems to handle that pretty well.

**Comment by oskarrough** [comment]
Good question and catch, thanks!

I don't think there's any reason to enable it by default. Let's change the default to `0`. Also the debounce should have `immediate: true` option set, so it calls at the start of each debounce-window — and not at the end.

**Comment by oskarrough** [comment]
Released in 1.2.0 :)
